In [89]:
import pandas as pd
import numpy as np

data = pd.read_csv ('train.csv')
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
allColumns = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Survived']
data = data [allColumns]
data.dropna ()
X = data [features]
y = data ['Survived']
X.head ()

Pclass     Sex  SibSp     Fare Embarked
0       3    male      1   7.2500        S
1       1  female      1  71.2833        C
2       3  female      0   7.9250        S
3       1  female      1  53.1000        S
4       3    male      0   8.0500        S

In [90]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct1 = ColumnTransformer ([('one_hot_encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array (ct1.fit_transform (X))
X = X [:, 1:]
print (X[:5])

ct2 = ColumnTransformer ([('one_hot_encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array (ct2.fit_transform (X))
X = X[:, 1:]
print (X[:5])

ct3 = ColumnTransformer ([('one_hot_encoder', OneHotEncoder(), [5])], remainder='passthrough')
X = np.array (ct3.fit_transform (X))
X = X[:, 1:]
print (X[:5])

[[0.0 1.0 'male' 1 7.25 'S']
 [0.0 0.0 'female' 1 71.2833 'C']
 [0.0 1.0 'female' 0 7.925 'S']
 [0.0 0.0 'female' 1 53.1 'S']
 [0.0 1.0 'male' 0 8.05 'S']]
[[1.0 0.0 1.0 1 7.25 'S']
 [0.0 0.0 0.0 1 71.2833 'C']
 [0.0 0.0 1.0 0 7.925 'S']
 [0.0 0.0 0.0 1 53.1 'S']
 [1.0 0.0 1.0 0 8.05 'S']]
[[0.0 1.0 0.0 1.0 0.0 1.0 1 7.25]
 [0.0 0.0 0.0 0.0 0.0 0.0 1 71.2833]
 [0.0 1.0 0.0 0.0 0.0 1.0 0 7.925]
 [0.0 1.0 0.0 0.0 0.0 0.0 1 53.1]
 [0.0 1.0 0.0 1.0 0.0 1.0 0 8.05]]


In [91]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
sc_X.fit (X)
X = sc_X.transform(X)
print (X[:5])

[[-0.30756234  0.61930636 -0.0474312   0.73769513 -0.51015154  0.90258736
   0.43279337 -0.50244517]
 [-0.30756234 -1.61470971 -0.0474312  -1.35557354 -0.51015154 -1.10792599
   0.43279337  0.78684529]
 [-0.30756234  0.61930636 -0.0474312  -1.35557354 -0.51015154  0.90258736
  -0.4745452  -0.48885426]
 [-0.30756234  0.61930636 -0.0474312  -1.35557354 -0.51015154 -1.10792599
   0.43279337  0.42073024]
 [-0.30756234  0.61930636 -0.0474312   0.73769513 -0.51015154  0.90258736
  -0.4745452  -0.48633742]]


In [92]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2, random_state = 1)

model = RandomForestClassifier (n_estimators = 500)

model.fit (X_train, y_train)

y_pred = model.predict (X_test)

correctAnswers = 0
for i in range (len (y_pred)):
    if y_pred [i] == y_test [y_test.index [i]]:
        correctAnswers += 1

print (correctAnswers/i)


0.7808988764044944
